# GET http://localhost:3000/gyms
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTMwMTU0NTAzfQ.pycu_-UHwwCtLHUMFWytkcAYB5sVYIFjXJ6QKKQIG58

# ###
# GET https://gymsauctionhouse-api-jsiopfmjry.now.sh/gyms
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTMwMTU0NTAzfQ.pycu_-UHwwCtLHUMFWytkcAYB5sVYIFjXJ6QKKQIG58


###
# GET http://localhost:3000/cars
GET http://localhost:3000/gyms